services:
  distrimax:
    build: .
    container_name: distrimax
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - distrimax_data:/var/lib/distrimax
    env_file:
      - .env
    networks:
      - mynetwork

volumes:
  distrimax_data:
    driver: local

networks:
  mynetwork:
    external: true